import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth/next';
import { authOptions } from '@/app/api/auth/[...nextauth]/route';
import { PrismaClient } from '@prisma/client';
import * as cheerio from 'cheerio'; // Import cheerio for helper

const prisma = new PrismaClient();

// --- Helper Function (Consider moving to lib/jobFetcher.ts) ---
async function fetchAndExtractJobText(url: string): Promise<string> {
  try {
    const response = await fetch(url, {
      headers: { 'User-Agent': 'Mozilla/5.0 (compatible; CVMatchBot/1.0; +http://YOUR_DOMAIN/bot)' }
    });
    if (!response.ok) {
      throw new Error(`Kunne ikke hente URL (${response.status})`);
    }
    const contentType = response.headers.get('content-type') || '';
    if (contentType.includes('application/pdf')) {
      throw new Error('PDF stillingsannonser støttes ikke ennå.');
    }
    const rawText = await response.text();
    const extractedText = contentType.includes('html') ? extractTextFromHtml(rawText) : rawText;
    if (!extractedText) {
        throw new Error('Kunne ikke hente ut tekst fra URLen.');
    }
    return extractedText;
  } catch (error) {
    console.error("fetchAndExtractJobText Error:", error);
    // Rethrow a user-friendly error message
    throw new Error(`Feil ved henting av stillingsannonse: ${error instanceof Error ? error.message : 'Ukjent feil'}`);
  }
}
// Helper needed by the above function
function extractTextFromHtml(html: string): string {
  const $ = cheerio.load(html);
  $('script, style, nav, header, footer').remove();
  const mainContent = $('.job-description, .position-body, .vacancy-text, article, main, .content-main').first();
  let jobText = mainContent.length > 0 ? mainContent.text() : $('body').text();
  return jobText.replace(/\s+/g, ' ').replace(/\n+/g, '\n').trim();
}
// --- End Helper Function ---


// POST /api/recruit/batches - Create a new job batch
export async function POST(request: NextRequest) {
  try {
    // 1. Get session and verify user is a logged-in recruiter
    const session = await getServerSession(authOptions);
    if (!session?.user?.id || session.user.role !== 'RECRUITER') {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    const userId = session.user.id;

    // 2. Get data from request body (expecting title, jobDescriptionUrl, description?)
    const { title, description, jobDescriptionUrl } = await request.json(); 

    // 3. Validate input
    if (!title || typeof title !== 'string' || title.trim() === '') {
      return NextResponse.json({ error: 'Tittel er påkrevd.' }, { status: 400 });
    }
    if (!jobDescriptionUrl || typeof jobDescriptionUrl !== 'string') {
       return NextResponse.json({ error: 'URL til stillingsannonse er påkrevd.' }, { status: 400 });
    }
    // Basic URL validation
    try { new URL(jobDescriptionUrl); } catch (_) {
        return NextResponse.json({ error: 'Ugyldig URL for stillingsannonse.' }, { status: 400 });
    }
    if (description && typeof description !== 'string') {
      return NextResponse.json({ error: 'Beskrivelse må være tekst.' }, { status: 400 });
    }

    // 4. Fetch and store Job Description Text
    let jobDescriptionText: string;
    try {
        console.log(`Fetching JD text for new batch from ${jobDescriptionUrl}`);
        jobDescriptionText = await fetchAndExtractJobText(jobDescriptionUrl);
        console.log(`Fetched JD text, length: ${jobDescriptionText.length}`);
    } catch (fetchError: any) {
        console.error("Failed to fetch/extract JD text during batch creation:", fetchError);
        return NextResponse.json({ error: `Kunne ikke hente stillingsannonse: ${fetchError.message}` }, { status: 400 });
    }
    
    // 5. Create Job Batch in Database
    const newBatch = await prisma.jobBatch.create({
      data: {
        userId: userId,
        title,
        description,
        jobDescriptionUrl,
        jobDescriptionText: jobDescriptionText,
        // widgetToken is automatically generated by Prisma's @default(cuid())
      },
      // Select the fields to return, including the new widgetToken
      select: {
        id: true,
        title: true,
        description: true,
        jobDescriptionUrl: true,
        widgetToken: true, // Ensure widgetToken is selected
        createdAt: true,
        updatedAt: true,
        userId: true,
      }
    });

    console.log(`New batch created: ${newBatch.id}, Widget Token: ${newBatch.widgetToken}`); // Log the token

    // 6. Return Success Response
    return NextResponse.json(newBatch, { status: 201 });

  } catch (error) {
    console.error('Error creating job batch:', error);
    if (error instanceof SyntaxError) {
      return NextResponse.json({ error: 'Ugyldig forespørsel format.' }, { status: 400 });
    }
    return NextResponse.json({ error: 'Kunne ikke opprette batch. En intern feil oppstod.' }, { status: 500 });
  }
} 